### ISSUE TITLE
If Run the MacOS M1

### ISSUE THREAD

**Issue by csh0101** [cozis/microtcp#2]
I have a problem with this project. If I want to run this on MacOS M1, how can i do this..
maybe there are have a handle book?.. I imagine, maybe i need to run this process by a virtual machine?

**Comment by cozis** [comment]
Hello! At the moment I'm not supporting MacOS because I don't own it. 

This is probably too technical, but MicroTCP depends on [libtuntap](https://github.com/LaKabane/libtuntap) for the gory OS-related details and its README states they support Darwin. This means it should be possible to adapt my code to make it work on MacOS. That's not a trivial fix though.

A virtual machine would definitely work. Your best bet is creating a docker container running Linux with MicroTCP in it
